### ISSUE TITLE
Add Xoshiro256StarStar

### ISSUE THREAD

**Issue by vemla-solutions** [rtmigo/xrandom#1]
Hello

Could you please add xoshiro256ss pseudorandom generator?
https://xoshiro.di.unimi.it/xoshiro256starstar.c

I understand it is mostly reusing xoshiro256pp but with a slight change.

Thank you in advance!

**Comment by rtmigo** [comment]
Hello!

Please, explain, what is the fundamental difference for you between star-star and plus-plus? For what cases would someone use the star-star?

**Comment by vemla-solutions** [comment]
It is used for UR encoding:
https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-005-ur.md#ur-encoding

"Hence seqNum and checksum are concatenated and then passed through a SHA256 hash to generate a 256-bit seed for a particular pseudorandom generator algorithm: Xoshiro256**, henceforth "Xoshiro256"."

**Comment by rtmigo** [comment]
The differences between ++ and ** were really quite small. 

I added the Xoshiro256** generator to the new version of the package (0.7.0) under the name `Xoshiro256ss`. The new version is already on pubdev.

**Comment by vemla-solutions** [comment]
Thank you, much appreciated.
