### ISSUE TITLE
Limit for max in nextInt should be 2^31 inclusive, not exclusive

### ISSUE THREAD

**Issue by Quijx** [rtmigo/xrandom#4]
If `nextInt(1 << 32)` is called on `Xrandom()` a `RangeError` is thrown. The same call on the dart `Random()` works fine because the limit for `max` is defined as `1 << 32` inclusively. The generated values will of course be in the range from 0 (inclusive) to `1 << 32` exclusive, so exactly 32 random bits.

The Problem is in the lines:
https://github.com/rtmigo/xrandom_dart/blob/8b4b47b8674f457add444241b7c29a96892e928d/lib/src/21_base32.dart#L83-L84

**Comment by Quijx** [comment]
Also, I would suggest to check if `max == 1 << 32` and directly return `nextRaw32()` in that case, which is more efficient because it saves the modulo and other operations. This might be usefull if a packages uses nextInt on the `Random` class (so without a dependency on `xrandom`) to get random bits. Then the user of that package could supply an `Xrandom()` as a generator and get slightly better performance.

**Comment by rtmigo** [comment]
That's right, the range limits are fixed in the new release (0.7.1).

**Comment by rtmigo** [comment]
> Also, I would suggest to check if `max == 1 << 32` and directly return `nextRaw32()`

We literally have only one `max` value, at which such `nextInt` will work noticeably faster. But there are more than four billion possible `max` values, at which such a `nextInt` will become slightly slower.

I have doubts that such an optimization is appropriate. Especially considering that for a particular `max == 1 << 32` there is a public `nextRaw32` method. And the `nextRaw32` is apparently even faster than an optimized `nextInt` would be.

Now the user has the opportunity to create a class that inherits `Xrandom` and overload the `nextInt` method with optimization for `nextRaw32`. I think it's worth leaving that decision to the user, whether they need it.

**Comment by Quijx** [comment]
I am currently writing a package that implements an `extension on Random` which adds a bunch of methods for generating random values of various types, for example `BigInt` or `Uint8List`. And since I don't want to add a dependeny to xrandom and the extension should work on any `Random`, I am using `nextInt(1 << 32)` a lot to generate random bytes. (And likely others do this too.) But i see that you have added a special case for all powers of two, which is even better. (The two extra `&` and `-` operations likely have absolutely negligible impact on performance.)
